module.exports = {
    table: 'personagem',
    values: [
        {
            id: '4c5d74c4-4e0a-11eb-ae93-0242ac130002',
            nome: "Kur",
            raca: "Elfo Noturno",
            classe: "Bruxo",
            nivel: 2,
            hp: 5,
            hp_maximo: 15,
            sanidade: 78,
            sanidade_maxima: 86,
            forca: 8,
            destreza: 15,
            constituicao: 14,
            inteligencia: 12,
            sabedoria: 10,
            carisma: 16,
            dado_vida: '1d8',
            npc: 0
        },
        {
            id: '4c5d76ea-4e0a-11eb-ae93-0242ac130002',
            nome: "Killua",
            raca: "Elfo Negro",
            classe: "Ladino",
            nivel: 2,
            hp: 8,
            hp_maximo: 8,
            sanidade: 47,
            sanidade_maxima: 61,
            forca: 13,
            destreza: 19,
            constituicao: 8,
            inteligencia: 14,
            sabedoria: 13,
            carisma: 10,
            dado_vida: '1d8',
            npc: 0
        },
        {
            id: '4c5d77da-4e0a-11eb-ae93-0242ac130002',
            nome: "Stevin",
            raca: "Humano",
            classe: "Bardo",
            nivel: 2,
            hp: 15,
            hp_maximo: 15,
            sanidade: 47,
            sanidade_maxima: 75,
            forca: 9,
            destreza: 15,
            constituicao: 11,
            inteligencia: 13,
            sabedoria: 14,
            carisma: 16,
            dado_vida: '1d8',
            npc: 0
        },
        {
            id: '4c5d7a6e-4e0a-11eb-ae93-0242ac130002',
            nome: "Ukah",
            raca: "Draconato",
            classe: "Guerreiro",
            nivel: 1,
            hp: 8,
            hp_maximo: 11,
            sanidade: 67,
            sanidade_maxima: 79,
            forca: 17,
            destreza: 13,
            constituicao: 12,
            inteligencia: 14,
            sabedoria: 8,
            carisma: 11,
            dado_vida: '1d10',
            npc: 0
        },
        {
            id: '4c5d7b4a-4e0a-11eb-ae93-0242ac130002',
            nome: "Rodimor",
            raca: "Elfo Noturno",
            classe: "Guerreiro",
            nivel: 5,
            hp: 30,
            hp_maximo: 30,
            sanidade: 60,
            sanidade_maxima: 80,
            forca: 17,
            destreza: 19,
            constituicao: 15,
            inteligencia: 13,
            sabedoria: 8,
            carisma: 10,
            dado_vida: '1d10+2',
            npc: 1
        },
    ]
};